version: '3'

services:
  nest-app:
    image: nest-blog-server-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - DATABASE_URL=your-database-url
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
